In [11]:
import pandas as pd
import unidecode as ud

In [12]:
df=pd.read_excel('FINAL_CANTONES.xlsx')
df.drop(['Unnamed: 6','Unnamed: 7', 'Unnamed: 8'], axis=1, inplace=True)
#drop the two last rows
df.drop(df.tail(2).index,inplace=True)
df

,PROVINCIA_CODIGO,PROVINCIA_CODIGO_STD,PROVINCIA_NOMBRE,CANTON_CODIGO,CANTON_NOMBRE,CANTON_CODIGO_STD
0,1.0,P01,AZUAY,260.0,CUENCA,C0101
1,1.0,P01,AZUAY,265.0,GUALACEO,C0103
2,1.0,P01,AZUAY,270.0,GIRÓN,C0102
3,1.0,P01,AZUAY,275.0,PAUTE,C0105
4,1.0,P01,AZUAY,280.0,SÍGSIG,C0109
...,...,...,...,...,...,...
269,28.0,P28,"LATAM, CARIBE, AFRICA",331.0,PERU,PER
270,28.0,P28,"LATAM, CARIBE, AFRICA",351.0,REPUBLICA DOMINICANA,DOM
271,28.0,P28,"LATAM, CARIBE, AFRICA",441.0,SUDAFRICA,ZAF
272,28.0,P28,"LATAM, CARIBE, AFRICA",391.0,URUGUAY,URY
273,28.0,P28,"LATAM, CARIBE, AFRICA",401.0,VENEZUELA,VEN

In [13]:
df.applymap(lambda x: ud.unidecode(x) if type(x) == str else x).to_csv('FINAL_CANTONES.csv', index=False)

C:\Users\saidm\AppData\Local\Temp\ipykernel_27756\2946327189.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: ud.unidecode(x) if type(x) == str else x).to_csv('FINAL_CANTONES.csv', index=False)